# Generated by Django 4.2.13 on 2024-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=50)),
                ('squad', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('psxg_ga_per90', models.FloatField()),
                ('nineties', models.FloatField()),
            ],
            options={
                'ordering': ['-psxg_ga_per90'],
            },
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('squad', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nineties', models.FloatField()),
                ('x_a', models.FloatField()),
                ('progressive_passes', models.FloatField()),
            ],
            options={
                'ordering': ['-x_a'],
            },
        ),
        migrations.CreateModel(
            name='PlayerNpGXG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('squad', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('minutes_played', models.FloatField()),
                ('goals', models.FloatField()),
                ('npxg', models.FloatField()),
                ('np_g_xg', models.FloatField()),
            ],
            options={
                'ordering': ['-np_g_xg'],
            },
        ),
        migrations.CreateModel(
            name='PlayerNpxG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('squad', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nineties', models.FloatField()),
                ('goals', models.FloatField()),
                ('npxg', models.FloatField()),
                ('np_g_xg', models.FloatField()),
            ],
            options={
                'ordering': ['-npxg'],
            },
        ),
        migrations.CreateModel(
            name='SquadIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(max_length=100)),
                ('matches_played', models.IntegerField()),
                ('points_per_match', models.FloatField()),
                ('last_5_results', models.CharField(max_length=5)),
                ('squad_moment_index', models.FloatField()),
                ('home_xgd_per90', models.FloatField()),
                ('away_xgd_per90', models.FloatField()),
            ],
            options={
                'ordering': ['-squad_moment_index'],
            },
        ),
        migrations.CreateModel(
            name='SquadXG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(max_length=100)),
                ('nineties', models.FloatField()),
                ('goals', models.FloatField()),
                ('xg', models.FloatField()),
                ('g_xg', models.FloatField()),
            ],
            options={
                'ordering': ['-xg'],
            },
        ),
        migrations.CreateModel(
            name='SquadXGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(max_length=255)),
                ('ninities', models.FloatField()),
                ('gls', models.FloatField()),
                ('xg', models.FloatField()),
                ('g_xg', models.FloatField()),
            ],
            options={
                'ordering': ['xg'],
            },
        ),
    ]
