# Generated by Django 4.2.13 on 2024-07-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brasileirao', '0003_rename_gls_squadxga_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playernpgxg',
            old_name='minutes_played',
            new_name='nineties',
        ),
    ]
