# Generated by Django 4.2.13 on 2024-07-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasileirao', '0006_rename_last_5_results_squadindex_last_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passing',
            name='prgp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playernpgxg',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playernpxg',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='squadxg',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='squadxga',
            name='goals',
            field=models.IntegerField(),
        ),
    ]
